version: "3.3"
services:

 # Laravel App
  phpfpm:
    container_name: ${APP_CONTAINER}
    ports:
      - ${PHPFPM_PORT}:9000
    build:
      args:
        user: ${LOCAL_USER}
        uid: ${LOCAL_UID}
      context: ./
      dockerfile: Dockerfile
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ${PROJECT_NAME}-network
    
  # Nginx Service
  nginx:
    container_name: ${WEB_CONTAINER}
    image: nginx:latest
    ports:
      - ${WEB_PORT}:80
    environment:
      SERVER_NAME: ${SERVER_NAME}
      WEB_PORT: ${WEB_PORT}
    volumes:
      - ./:/var/www
      - ./config/nginx/templates:/etc/nginx/templates:rw,cached
    networks:
      - ${PROJECT_NAME}-network

  # Postgres Service
  db:
    container_name: ${DB_CONTAINER}
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - ${PROJECT_NAME}-network
      
networks:
  polimerka-network:
    driver: bridge
